parameters:
  placeholder.empty_string: ''
  placeholder.true: true
  placeholder.false: false
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  SomeBdyElse\SymfonyEnvVariables\:
    resource: '../Classes/*'

  Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'

  SomeBdyElse\SymfonyEnvVariables\EnvironmentVariables\EnvironmentVariableRetreiver:
    arguments:
      $container: '@service_container'
      $processors: '@container.env_var_processors_locator'
